spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:/local:3306/big_event
    username: root
    password: 123456


mybatis:
  configuration:
    map-underscore-to-camel-case: true


##   get_token  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